drop USER
if EXISTS 'admin_001'@'%';

SELECT 'ADDING user admin_001' AS 'INSTALLATION PROGRESSING';

CREATE USER
if NOT  EXISTS 'admin_001'@'%'
IDENTIFIED BY 'guttmanGrizzlies_2024'

WITH
-- SET RESOURCE LIMITS
 MAX_QUERIES_PER_HOUR 20
 MAX_UPDATES_PER_HOUR 10
 MAX_CONNECTIONS_PER_HOUR 5
 MAX_USER_CONNECTIONS 2

-- SET PASSWORD OPTIONS
 FAILED_LOGIN_ATTEMPTS 10
 PASSWORD_LOCK_TIME UNBOUNDED
 PASSWORD EXPIRE INTERVAL 90 DAY
 PASSWORD HISTORY 5
 PASSWORD REUSE INTERVAL 365 DAY;

 REVOKE ALL, GRANT OPTION FROM 'ADMIN_001'@'%';

 SELECT user, show_db_priv, account_locked
 FROM mysql.user;

 FLUSH PRIVILEGES;

 SELECT user, show_db_priv, account_locked
 FROM mysql.user;

 -- GRANT PRIVILEGES
 GRANT SELECT
 ON classicmodels.*
 TO 'read_only_classicmodels_db'@'%';

 GRANT CREATE
 ON *.*
 TO 'admin_user'@'%';

 GRANT INSERT, UPDATE
 ON employees.employees
 TO 'app_user'@'%';

GRANT SELECT
ON employees.*
TO 'read_only_employees_db'@'%';

FLUSH PRIVILEGES




